// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package sqlcgen

import (
	"context"
)

const checkPostgres = `-- name: CheckPostgres :one
SELECT 1::bigint AS ok
`

func (q *Queries) CheckPostgres(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, checkPostgres)
	var ok int64
	err := row.Scan(&ok)
	return ok, err
}
