// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateDeploymentsByDay = `-- name: AggregateDeploymentsByDay :many
SELECT DATE(deployed_at AT TIME ZONE 'UTC') AS metric_date,
       COUNT(*) FILTER (WHERE status = 'success')::bigint AS successful_deployment_count,
       COUNT(*) FILTER (WHERE status = 'failed')::bigint AS failed_deployment_count
FROM deployments
WHERE repository_id = $1
  AND deployed_at >= $2
  AND deployed_at < $3
GROUP BY DATE(deployed_at AT TIME ZONE 'UTC')
ORDER BY metric_date
`

type AggregateDeploymentsByDayParams struct {
	RepositoryID pgtype.UUID
	DeployedAt   pgtype.Timestamptz
	DeployedAt_2 pgtype.Timestamptz
}

type AggregateDeploymentsByDayRow struct {
	MetricDate                pgtype.Date
	SuccessfulDeploymentCount int64
	FailedDeploymentCount     int64
}

func (q *Queries) AggregateDeploymentsByDay(ctx context.Context, arg AggregateDeploymentsByDayParams) ([]AggregateDeploymentsByDayRow, error) {
	rows, err := q.db.Query(ctx, aggregateDeploymentsByDay, arg.RepositoryID, arg.DeployedAt, arg.DeployedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateDeploymentsByDayRow
	for rows.Next() {
		var i AggregateDeploymentsByDayRow
		if err := rows.Scan(&i.MetricDate, &i.SuccessfulDeploymentCount, &i.FailedDeploymentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregatePRCycleByDay = `-- name: AggregatePRCycleByDay :many
SELECT DATE(pr.merged_at AT TIME ZONE 'UTC') AS metric_date,
       COUNT(*)::bigint AS merged_pr_count,
       COALESCE(AVG(EXTRACT(EPOCH FROM (pr.merged_at - pr.created_at)) / 60.0), 0)::double precision AS pr_cycle_time_minutes
FROM pull_requests pr
WHERE pr.repository_id = $1
  AND pr.merged_at IS NOT NULL
  AND pr.merged_at >= $2
  AND pr.merged_at < $3
  AND pr.is_draft = FALSE
GROUP BY DATE(pr.merged_at AT TIME ZONE 'UTC')
ORDER BY metric_date
`

type AggregatePRCycleByDayParams struct {
	RepositoryID pgtype.UUID
	MergedAt     pgtype.Timestamptz
	MergedAt_2   pgtype.Timestamptz
}

type AggregatePRCycleByDayRow struct {
	MetricDate         pgtype.Date
	MergedPrCount      int64
	PrCycleTimeMinutes float64
}

func (q *Queries) AggregatePRCycleByDay(ctx context.Context, arg AggregatePRCycleByDayParams) ([]AggregatePRCycleByDayRow, error) {
	rows, err := q.db.Query(ctx, aggregatePRCycleByDay, arg.RepositoryID, arg.MergedAt, arg.MergedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregatePRCycleByDayRow
	for rows.Next() {
		var i AggregatePRCycleByDayRow
		if err := rows.Scan(&i.MetricDate, &i.MergedPrCount, &i.PrCycleTimeMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregatePRSizeByDay = `-- name: AggregatePRSizeByDay :many
WITH review_counts AS (
    SELECT pull_request_id, COUNT(*) AS review_count
    FROM pull_request_reviews
    GROUP BY pull_request_id
)
SELECT DATE(pr.created_at AT TIME ZONE 'UTC') AS metric_date,
       COUNT(*)::bigint AS pr_count,
       COUNT(*) FILTER (WHERE COALESCE(rc.review_count, 0) > 0)::bigint AS reviewed_pr_count,
       COALESCE(AVG(pr.files_changed)::double precision, 0)::double precision AS average_files_changed,
       COALESCE(AVG(pr.additions)::double precision, 0)::double precision AS average_additions,
       COALESCE(AVG(pr.deletions)::double precision, 0)::double precision AS average_deletions
FROM pull_requests pr
LEFT JOIN review_counts rc ON rc.pull_request_id = pr.id
WHERE pr.repository_id = $1
  AND pr.created_at >= $2
  AND pr.created_at < $3
  AND pr.is_draft = FALSE
GROUP BY DATE(pr.created_at AT TIME ZONE 'UTC')
ORDER BY metric_date
`

type AggregatePRSizeByDayParams struct {
	RepositoryID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	CreatedAt_2  pgtype.Timestamptz
}

type AggregatePRSizeByDayRow struct {
	MetricDate          pgtype.Date
	PrCount             int64
	ReviewedPrCount     int64
	AverageFilesChanged float64
	AverageAdditions    float64
	AverageDeletions    float64
}

func (q *Queries) AggregatePRSizeByDay(ctx context.Context, arg AggregatePRSizeByDayParams) ([]AggregatePRSizeByDayRow, error) {
	rows, err := q.db.Query(ctx, aggregatePRSizeByDay, arg.RepositoryID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregatePRSizeByDayRow
	for rows.Next() {
		var i AggregatePRSizeByDayRow
		if err := rows.Scan(
			&i.MetricDate,
			&i.PrCount,
			&i.ReviewedPrCount,
			&i.AverageFilesChanged,
			&i.AverageAdditions,
			&i.AverageDeletions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateReviewMetricsByDay = `-- name: AggregateReviewMetricsByDay :many
SELECT DATE(pr.created_at AT TIME ZONE 'UTC') AS metric_date,
       COUNT(*) FILTER (
           WHERE rev.review_requested_at IS NOT NULL
             AND rev.first_review_at IS NOT NULL
       )::bigint AS review_wait_sample_count,
       COALESCE(AVG(EXTRACT(EPOCH FROM (rev.first_review_at - rev.review_requested_at)) / 60.0) FILTER (
           WHERE rev.review_requested_at IS NOT NULL
             AND rev.first_review_at IS NOT NULL
       ), 0)::double precision AS average_review_wait_minutes,
       COUNT(*) FILTER (
           WHERE rev.review_requested_at IS NOT NULL
             AND rev.review_submitted_at IS NOT NULL
       )::bigint AS review_time_sample_count,
       COALESCE(AVG(EXTRACT(EPOCH FROM (rev.review_submitted_at - rev.review_requested_at)) / 60.0) FILTER (
           WHERE rev.review_requested_at IS NOT NULL
             AND rev.review_submitted_at IS NOT NULL
       ), 0)::double precision AS average_review_minutes
FROM pull_requests pr
LEFT JOIN pull_request_reviews rev ON rev.pull_request_id = pr.id
WHERE pr.repository_id = $1
  AND pr.created_at >= $2
  AND pr.created_at < $3
  AND pr.is_draft = FALSE
GROUP BY DATE(pr.created_at AT TIME ZONE 'UTC')
ORDER BY metric_date
`

type AggregateReviewMetricsByDayParams struct {
	RepositoryID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	CreatedAt_2  pgtype.Timestamptz
}

type AggregateReviewMetricsByDayRow struct {
	MetricDate               pgtype.Date
	ReviewWaitSampleCount    int64
	AverageReviewWaitMinutes float64
	ReviewTimeSampleCount    int64
	AverageReviewMinutes     float64
}

func (q *Queries) AggregateReviewMetricsByDay(ctx context.Context, arg AggregateReviewMetricsByDayParams) ([]AggregateReviewMetricsByDayRow, error) {
	rows, err := q.db.Query(ctx, aggregateReviewMetricsByDay, arg.RepositoryID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateReviewMetricsByDayRow
	for rows.Next() {
		var i AggregateReviewMetricsByDayRow
		if err := rows.Scan(
			&i.MetricDate,
			&i.ReviewWaitSampleCount,
			&i.AverageReviewWaitMinutes,
			&i.ReviewTimeSampleCount,
			&i.AverageReviewMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsForAnalytics = `-- name: ListDeploymentsForAnalytics :many
SELECT id, repository_id, environment, status, deployed_at
FROM deployments
WHERE repository_id = $1
  AND deployed_at >= $2
  AND deployed_at < $3
ORDER BY deployed_at ASC
`

type ListDeploymentsForAnalyticsParams struct {
	RepositoryID pgtype.UUID
	DeployedAt   pgtype.Timestamptz
	DeployedAt_2 pgtype.Timestamptz
}

func (q *Queries) ListDeploymentsForAnalytics(ctx context.Context, arg ListDeploymentsForAnalyticsParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsForAnalytics, arg.RepositoryID, arg.DeployedAt, arg.DeployedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Environment,
			&i.Status,
			&i.DeployedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileChangesForAnalytics = `-- name: ListFileChangesForAnalytics :many
SELECT fc.id, fc.pull_request_id, fc.file_path, fc.additions, fc.deletions, fc.commit_count
FROM file_changes fc
INNER JOIN pull_requests pr ON pr.id = fc.pull_request_id
WHERE pr.repository_id = $1
  AND pr.created_at >= $2
  AND pr.created_at < $3
ORDER BY fc.id ASC
`

type ListFileChangesForAnalyticsParams struct {
	RepositoryID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	CreatedAt_2  pgtype.Timestamptz
}

func (q *Queries) ListFileChangesForAnalytics(ctx context.Context, arg ListFileChangesForAnalyticsParams) ([]FileChange, error) {
	rows, err := q.db.Query(ctx, listFileChangesForAnalytics, arg.RepositoryID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileChange
	for rows.Next() {
		var i FileChange
		if err := rows.Scan(
			&i.ID,
			&i.PullRequestID,
			&i.FilePath,
			&i.Additions,
			&i.Deletions,
			&i.CommitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestReviewsForAnalytics = `-- name: ListPullRequestReviewsForAnalytics :many
SELECT prr.id, prr.pull_request_id, prr.github_review_id, prr.reviewer, prr.review_requested_at, prr.first_review_at, prr.review_submitted_at, prr.state
FROM pull_request_reviews prr
INNER JOIN pull_requests pr ON pr.id = prr.pull_request_id
WHERE pr.repository_id = $1
  AND pr.created_at < $3
  AND (pr.merged_at IS NULL OR pr.merged_at >= $2 OR pr.created_at >= $2)
ORDER BY prr.id ASC
`

type ListPullRequestReviewsForAnalyticsParams struct {
	RepositoryID pgtype.UUID
	MergedAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListPullRequestReviewsForAnalytics(ctx context.Context, arg ListPullRequestReviewsForAnalyticsParams) ([]PullRequestReview, error) {
	rows, err := q.db.Query(ctx, listPullRequestReviewsForAnalytics, arg.RepositoryID, arg.MergedAt, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequestReview
	for rows.Next() {
		var i PullRequestReview
		if err := rows.Scan(
			&i.ID,
			&i.PullRequestID,
			&i.GithubReviewID,
			&i.Reviewer,
			&i.ReviewRequestedAt,
			&i.FirstReviewAt,
			&i.ReviewSubmittedAt,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestsForAnalytics = `-- name: ListPullRequestsForAnalytics :many
SELECT id, repository_id, github_pr_id, number, title, author, state, created_at, merged_at, closed_at, additions, deletions, files_changed, is_draft
FROM pull_requests
WHERE repository_id = $1
  AND created_at < $3
  AND (merged_at IS NULL OR merged_at >= $2 OR created_at >= $2)
ORDER BY created_at ASC
`

type ListPullRequestsForAnalyticsParams struct {
	RepositoryID pgtype.UUID
	MergedAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListPullRequestsForAnalytics(ctx context.Context, arg ListPullRequestsForAnalyticsParams) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, listPullRequestsForAnalytics, arg.RepositoryID, arg.MergedAt, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.GithubPrID,
			&i.Number,
			&i.Title,
			&i.Author,
			&i.State,
			&i.CreatedAt,
			&i.MergedAt,
			&i.ClosedAt,
			&i.Additions,
			&i.Deletions,
			&i.FilesChanged,
			&i.IsDraft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
