// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metric_definitions.sql

package sqlcgen

import (
	"context"
)

const getActiveMetricDefinitionByKey = `-- name: GetActiveMetricDefinitionByKey :one
SELECT id,
       metric_key,
       name,
       metric_version,
       algorithm_version,
       unit,
       description,
       config_json,
       is_active,
       created_at,
       created_by,
       updated_at,
       updated_by,
       deleted_at,
       deleted_by
FROM metric_definitions
WHERE metric_key = $1
  AND is_active = TRUE
  AND deleted_at IS NULL
ORDER BY metric_version DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveMetricDefinitionByKey(ctx context.Context, metricKey string) (MetricDefinition, error) {
	row := q.db.QueryRow(ctx, getActiveMetricDefinitionByKey, metricKey)
	var i MetricDefinition
	err := row.Scan(
		&i.ID,
		&i.MetricKey,
		&i.Name,
		&i.MetricVersion,
		&i.AlgorithmVersion,
		&i.Unit,
		&i.Description,
		&i.ConfigJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
