// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deployment struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Environment  string
	Status       string
	DeployedAt   pgtype.Timestamptz
}

type FileChange struct {
	ID            pgtype.UUID
	PullRequestID pgtype.UUID
	FilePath      string
	Additions     int32
	Deletions     int32
	CommitCount   int32
}

type GithubInstallation struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	InstallationID pgtype.Int8
	InstalledAt    pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	GithubID  int64
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	Slug      string
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}

type PullRequest struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	GithubPrID   int64
	Number       int32
	Title        string
	Author       string
	State        string
	CreatedAt    pgtype.Timestamptz
	MergedAt     pgtype.Timestamptz
	ClosedAt     pgtype.Timestamptz
	Additions    int32
	Deletions    int32
	FilesChanged int32
	IsDraft      bool
}

type PullRequestReview struct {
	ID                pgtype.UUID
	PullRequestID     pgtype.UUID
	GithubReviewID    int64
	Reviewer          string
	ReviewRequestedAt pgtype.Timestamptz
	FirstReviewAt     pgtype.Timestamptz
	ReviewSubmittedAt pgtype.Timestamptz
	State             string
}

type Repository struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	GithubID       int64
	Name           string
	FullName       string
	DefaultBranch  pgtype.Text
	IsActive       bool
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ArchivedAt     pgtype.Timestamptz
}

type SyncJob struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID               pgtype.UUID
	RepositoryID     pgtype.UUID
	GithubDeliveryID pgtype.Text
	EventType        pgtype.Text
	Processed        bool
	ReceivedAt       pgtype.Timestamptz
	Action           pgtype.Text
	Payload          []byte
	SyncJobID        pgtype.UUID
	UpdatedAt        pgtype.Timestamptz
}
