// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubInstallation struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	InstallationID pgtype.Int8
	InstalledAt    pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	GithubID  int64
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	Slug      string
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}

type Repository struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	GithubID       int64
	Name           string
	FullName       string
	DefaultBranch  pgtype.Text
	IsActive       bool
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ArchivedAt     pgtype.Timestamptz
}

type SyncJob struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       pgtype.Text
	Progress     int32
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID               pgtype.UUID
	RepositoryID     pgtype.UUID
	GithubDeliveryID pgtype.Text
	EventType        pgtype.Text
	Processed        bool
	ReceivedAt       pgtype.Timestamptz
}
