// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	ActorUserID    pgtype.UUID
	Action         string
	ResourceType   string
	ResourceID     pgtype.UUID
	MetadataJson   []byte
	CreatedAt      pgtype.Timestamptz
}

type CommitEvent struct {
	ID              pgtype.UUID
	RepositoryID    pgtype.UUID
	GithubCommitSha string
	Author          string
	AuthorEmail     pgtype.Text
	Message         string
	AuthoredAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Deployment struct {
	ID                 pgtype.UUID
	RepositoryID       pgtype.UUID
	Environment        string
	Status             string
	DeployedAt         pgtype.Timestamptz
	GithubDeploymentID pgtype.Int8
}

type FileChange struct {
	ID            pgtype.UUID
	PullRequestID pgtype.UUID
	FilePath      string
	Additions     int32
	Deletions     int32
	CommitCount   int32
}

type GithubInstallation struct {
	ID                      pgtype.UUID
	OrganizationID          pgtype.UUID
	InstallationID          pgtype.Int8
	InstalledAt             pgtype.Timestamptz
	AccountLogin            pgtype.Text
	AccountType             pgtype.Text
	TargetType              pgtype.Text
	Status                  string
	PermissionsJson         []byte
	InstalledByGithubUserID pgtype.Int8
	SuspendedAt             pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	DisconnectedAt          pgtype.Timestamptz
}

type GithubInstallationRepository struct {
	ID                   pgtype.UUID
	GithubInstallationID pgtype.UUID
	GithubRepositoryID   int64
	Name                 string
	OwnerLogin           string
	FullName             string
	Private              bool
	DefaultBranch        pgtype.Text
	InstallationStatus   string
	SelectionStatus      string
	PermissionsJson      []byte
	LinkedRepositoryID   pgtype.UUID
	LastSyncedAt         pgtype.Timestamptz
	SyncErrorMessage     pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	LastDiscoveredAt     pgtype.Timestamptz
}

type InsightStatus struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	RepositoryID   pgtype.UUID
	InsightKey     string
	InsightType    string
	Status         string
	EvidenceJson   []byte
	ReviewedBy     pgtype.UUID
	ReviewedAt     pgtype.Timestamptz
	DismissedAt    pgtype.Timestamptz
	ReopenedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	GithubID  int64
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	Slug      string
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}

type PullRequest struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	GithubPrID   int64
	Number       int32
	Title        string
	Author       string
	State        string
	CreatedAt    pgtype.Timestamptz
	MergedAt     pgtype.Timestamptz
	ClosedAt     pgtype.Timestamptz
	Additions    int32
	Deletions    int32
	FilesChanged int32
	IsDraft      bool
}

type PullRequestReview struct {
	ID                pgtype.UUID
	PullRequestID     pgtype.UUID
	GithubReviewID    int64
	Reviewer          string
	ReviewRequestedAt pgtype.Timestamptz
	FirstReviewAt     pgtype.Timestamptz
	ReviewSubmittedAt pgtype.Timestamptz
	State             string
}

type Repository struct {
	ID                             pgtype.UUID
	OrganizationID                 pgtype.UUID
	GithubID                       int64
	Name                           string
	FullName                       string
	DefaultBranch                  pgtype.Text
	IsActive                       bool
	LastSyncedAt                   pgtype.Timestamptz
	CreatedAt                      pgtype.Timestamptz
	UpdatedAt                      pgtype.Timestamptz
	ArchivedAt                     pgtype.Timestamptz
	GithubInstallationRepositoryID pgtype.UUID
	InitialSyncStatus              pgtype.Text
	InitialSyncCompletedAt         pgtype.Timestamptz
	SyncErrorMessage               pgtype.Text
}

type SyncCheckpoint struct {
	ID              pgtype.UUID
	SyncJobID       pgtype.UUID
	RepositoryID    pgtype.UUID
	ResourceType    string
	CheckpointKey   string
	CheckpointValue pgtype.Text
	Status          string
	LastProcessedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type SyncJob struct {
	ID             pgtype.UUID
	RepositoryID   pgtype.UUID
	Status         string
	Progress       int32
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	TriggeredBy    pgtype.UUID
	ErrorMessage   pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	JobType        string
	IdempotencyKey pgtype.Text
	ErrorCode      pgtype.Text
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type UserSession struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	AccessTokenHash  string
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	RefreshExpiresAt pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	UserAgent        pgtype.Text
	IpAddress        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID                    pgtype.UUID
	RepositoryID          pgtype.UUID
	GithubDeliveryID      pgtype.Text
	EventType             pgtype.Text
	Processed             bool
	ReceivedAt            pgtype.Timestamptz
	Action                pgtype.Text
	Payload               []byte
	SyncJobID             pgtype.UUID
	UpdatedAt             pgtype.Timestamptz
	GithubInstallationID  pgtype.UUID
	ProcessingStatus      string
	PayloadRetentionUntil pgtype.Timestamptz
	ErrorMessage          pgtype.Text
	ProcessedAt           pgtype.Timestamptz
	RetryCount            int32
	NextRetryAt           pgtype.Timestamptz
}

type WorkflowEvent struct {
	ID                  pgtype.UUID
	RepositoryID        pgtype.UUID
	GithubWorkflowRunID int64
	WorkflowName        string
	Status              pgtype.Text
	Conclusion          pgtype.Text
	StartedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
