// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_members.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationOwners = `-- name: CountOrganizationOwners :one
SELECT COUNT(*)::bigint
FROM organization_members
WHERE organization_id = $1
  AND role = 'owner'
`

func (q *Queries) CountOrganizationOwners(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationOwners, organizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO organization_members (
    id,
    organization_id,
    user_id,
    role
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, organization_id, user_id, role
`

type CreateOrganizationMemberParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const deleteOrganizationMember = `-- name: DeleteOrganizationMember :execrows
DELETE FROM organization_members
WHERE id = $1
`

func (q *Queries) DeleteOrganizationMember(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrganizationMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrganizationMemberByID = `-- name: GetOrganizationMemberByID :one
SELECT id, organization_id, user_id, role
FROM organization_members
WHERE id = $1
`

func (q *Queries) GetOrganizationMemberByID(ctx context.Context, id pgtype.UUID) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberByID, id)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT id, organization_id, user_id, role
FROM organization_members
WHERE organization_id = $1
ORDER BY id ASC
`

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID pgtype.UUID) ([]OrganizationMember, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationMember
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationExists = `-- name: OrganizationExists :one
SELECT EXISTS (
    SELECT 1
    FROM organizations
    WHERE id = $1
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) OrganizationExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, organizationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateOrganizationMemberRole = `-- name: UpdateOrganizationMemberRole :one
UPDATE organization_members
SET role = $2
WHERE id = $1
RETURNING id, organization_id, user_id, role
`

type UpdateOrganizationMemberRoleParams struct {
	ID   pgtype.UUID
	Role string
}

func (q *Queries) UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMemberRole, arg.ID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE id = $1
) AS exists
`

func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
