// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*)::bigint
FROM organizations
WHERE deleted_at IS NULL
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    id,
    github_id,
    slug,
    name
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, github_id, slug, name, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID       pgtype.UUID
	GithubID int64
	Slug     string
	Name     pgtype.Text
}

type CreateOrganizationRow struct {
	ID        pgtype.UUID
	GithubID  int64
	Slug      string
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.GithubID,
		arg.Slug,
		arg.Name,
	)
	var i CreateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, github_id, slug, name, created_at, updated_at
FROM organizations
WHERE id = $1
  AND deleted_at IS NULL
`

type GetOrganizationByIDRow struct {
	ID        pgtype.UUID
	GithubID  int64
	Slug      string
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (GetOrganizationByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i GetOrganizationByIDRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, github_id, slug, name, created_at, updated_at
FROM organizations
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32
	Offset int32
}

type ListOrganizationsRow struct {
	ID        pgtype.UUID
	GithubID  int64
	Slug      string
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsRow
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :one
UPDATE organizations
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteOrganization, id)
	err := row.Scan(&id)
	return id, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET slug = $2,
    name = $3,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, github_id, slug, name, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID   pgtype.UUID
	Slug string
	Name pgtype.Text
}

type UpdateOrganizationRow struct {
	ID        pgtype.UUID
	GithubID  int64
	Slug      string
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.ID, arg.Slug, arg.Name)
	var i UpdateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
