// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_retention_settings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrganizationRetentionSettings = `-- name: GetOrganizationRetentionSettings :one
SELECT organization_id,
       analytics_raw_retention_days,
       created_at,
       updated_at,
       updated_by
FROM organization_retention_settings
WHERE organization_id = $1
`

func (q *Queries) GetOrganizationRetentionSettings(ctx context.Context, organizationID pgtype.UUID) (OrganizationRetentionSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationRetentionSettings, organizationID)
	var i OrganizationRetentionSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.AnalyticsRawRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertOrganizationRetentionSettings = `-- name: UpsertOrganizationRetentionSettings :one
INSERT INTO organization_retention_settings (
    organization_id, analytics_raw_retention_days, created_at, updated_at, updated_by
) VALUES (
    $1, $2, NOW(), NOW(), $3
)
ON CONFLICT (organization_id) DO UPDATE SET
    analytics_raw_retention_days = EXCLUDED.analytics_raw_retention_days,
    updated_at = NOW(),
    updated_by = EXCLUDED.updated_by
RETURNING organization_id,
          analytics_raw_retention_days,
          created_at,
          updated_at,
          updated_by
`

type UpsertOrganizationRetentionSettingsParams struct {
	OrganizationID            pgtype.UUID
	AnalyticsRawRetentionDays pgtype.Int4
	UpdatedBy                 pgtype.UUID
}

func (q *Queries) UpsertOrganizationRetentionSettings(ctx context.Context, arg UpsertOrganizationRetentionSettingsParams) (OrganizationRetentionSetting, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationRetentionSettings, arg.OrganizationID, arg.AnalyticsRawRetentionDays, arg.UpdatedBy)
	var i OrganizationRetentionSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.AnalyticsRawRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
