// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_rule_settings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrganizationRuleSettings = `-- name: GetOrganizationRuleSettings :one
SELECT organization_id,
       config_json,
       created_at,
       updated_at,
       updated_by
FROM organization_rule_settings
WHERE organization_id = $1
`

func (q *Queries) GetOrganizationRuleSettings(ctx context.Context, organizationID pgtype.UUID) (OrganizationRuleSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationRuleSettings, organizationID)
	var i OrganizationRuleSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertOrganizationRuleSettings = `-- name: UpsertOrganizationRuleSettings :one
INSERT INTO organization_rule_settings (
    organization_id, config_json, created_at, updated_at, updated_by
) VALUES (
    $1, $2, NOW(), NOW(), $3
)
ON CONFLICT (organization_id) DO UPDATE SET
    config_json = EXCLUDED.config_json,
    updated_at = NOW(),
    updated_by = EXCLUDED.updated_by
RETURNING organization_id,
          config_json,
          created_at,
          updated_at,
          updated_by
`

type UpsertOrganizationRuleSettingsParams struct {
	OrganizationID pgtype.UUID
	ConfigJson     []byte
	UpdatedBy      pgtype.UUID
}

func (q *Queries) UpsertOrganizationRuleSettings(ctx context.Context, arg UpsertOrganizationRuleSettingsParams) (OrganizationRuleSetting, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationRuleSettings, arg.OrganizationID, arg.ConfigJson, arg.UpdatedBy)
	var i OrganizationRuleSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
