// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_requests.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertPullRequest = `-- name: UpsertPullRequest :one
INSERT INTO pull_requests (
    id,
    repository_id,
    github_pr_id,
    number,
    title,
    author,
    state,
    created_at,
    merged_at,
    closed_at,
    additions,
    deletions,
    files_changed,
    is_draft
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
ON CONFLICT (github_pr_id) DO UPDATE SET
    repository_id = EXCLUDED.repository_id,
    number = EXCLUDED.number,
    title = EXCLUDED.title,
    author = EXCLUDED.author,
    state = EXCLUDED.state,
    created_at = EXCLUDED.created_at,
    merged_at = EXCLUDED.merged_at,
    closed_at = EXCLUDED.closed_at,
    additions = EXCLUDED.additions,
    deletions = EXCLUDED.deletions,
    files_changed = EXCLUDED.files_changed,
    is_draft = EXCLUDED.is_draft
RETURNING id
`

type UpsertPullRequestParams struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	GithubPrID   int64
	Number       int32
	Title        string
	Author       string
	State        string
	CreatedAt    pgtype.Timestamptz
	MergedAt     pgtype.Timestamptz
	ClosedAt     pgtype.Timestamptz
	Additions    int32
	Deletions    int32
	FilesChanged int32
	IsDraft      bool
}

func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPullRequest,
		arg.ID,
		arg.RepositoryID,
		arg.GithubPrID,
		arg.Number,
		arg.Title,
		arg.Author,
		arg.State,
		arg.CreatedAt,
		arg.MergedAt,
		arg.ClosedAt,
		arg.Additions,
		arg.Deletions,
		arg.FilesChanged,
		arg.IsDraft,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertPullRequestReview = `-- name: UpsertPullRequestReview :exec
INSERT INTO pull_request_reviews (
    id,
    pull_request_id,
    github_review_id,
    reviewer,
    review_requested_at,
    first_review_at,
    review_submitted_at,
    state
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (github_review_id) DO UPDATE SET
    pull_request_id = EXCLUDED.pull_request_id,
    reviewer = EXCLUDED.reviewer,
    review_requested_at = EXCLUDED.review_requested_at,
    first_review_at = EXCLUDED.first_review_at,
    review_submitted_at = EXCLUDED.review_submitted_at,
    state = EXCLUDED.state
`

type UpsertPullRequestReviewParams struct {
	ID                pgtype.UUID
	PullRequestID     pgtype.UUID
	GithubReviewID    int64
	Reviewer          string
	ReviewRequestedAt pgtype.Timestamptz
	FirstReviewAt     pgtype.Timestamptz
	ReviewSubmittedAt pgtype.Timestamptz
	State             string
}

func (q *Queries) UpsertPullRequestReview(ctx context.Context, arg UpsertPullRequestReviewParams) error {
	_, err := q.db.Exec(ctx, upsertPullRequestReview,
		arg.ID,
		arg.PullRequestID,
		arg.GithubReviewID,
		arg.Reviewer,
		arg.ReviewRequestedAt,
		arg.FirstReviewAt,
		arg.ReviewSubmittedAt,
		arg.State,
	)
	return err
}
