// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRepositories = `-- name: CountRepositories :one
SELECT COUNT(*)::bigint
FROM repositories
WHERE organization_id = $1
  AND (
    $2 = ''
    OR ($2 = 'active' AND archived_at IS NULL AND is_active = TRUE)
    OR ($2 = 'inactive' AND archived_at IS NULL AND is_active = FALSE)
    OR ($2 = 'archived' AND archived_at IS NOT NULL)
  )
  AND (
    $3 = ''
    OR name ILIKE '%' || $3 || '%'
    OR full_name ILIKE '%' || $3 || '%'
  )
`

type CountRepositoriesParams struct {
	OrganizationID pgtype.UUID
	Column2        interface{}
	Column3        interface{}
}

func (q *Queries) CountRepositories(ctx context.Context, arg CountRepositoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRepositories, arg.OrganizationID, arg.Column2, arg.Column3)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
    id,
    organization_id,
    github_id,
    name,
    full_name,
    default_branch,
    is_active,
    archived_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, organization_id, github_id, name, full_name, default_branch, is_active, archived_at, last_synced_at, created_at, updated_at
`

type CreateRepositoryParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	GithubID       int64
	Name           string
	FullName       string
	DefaultBranch  pgtype.Text
	IsActive       bool
	ArchivedAt     pgtype.Timestamptz
}

type CreateRepositoryRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	GithubID       int64
	Name           string
	FullName       string
	DefaultBranch  pgtype.Text
	IsActive       bool
	ArchivedAt     pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (CreateRepositoryRow, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.ID,
		arg.OrganizationID,
		arg.GithubID,
		arg.Name,
		arg.FullName,
		arg.DefaultBranch,
		arg.IsActive,
		arg.ArchivedAt,
	)
	var i CreateRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubID,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.IsActive,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByGithubID = `-- name: GetRepositoryByGithubID :one
SELECT id, organization_id, github_id, name, full_name, default_branch, is_active, archived_at, last_synced_at, created_at, updated_at
FROM repositories
WHERE github_id = $1
`

type GetRepositoryByGithubIDRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	GithubID       int64
	Name           string
	FullName       string
	DefaultBranch  pgtype.Text
	IsActive       bool
	ArchivedAt     pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetRepositoryByGithubID(ctx context.Context, githubID int64) (GetRepositoryByGithubIDRow, error) {
	row := q.db.QueryRow(ctx, getRepositoryByGithubID, githubID)
	var i GetRepositoryByGithubIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubID,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.IsActive,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, organization_id, github_id, name, full_name, default_branch, is_active, archived_at, last_synced_at, created_at, updated_at
FROM repositories
WHERE id = $1
`

type GetRepositoryByIDRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	GithubID       int64
	Name           string
	FullName       string
	DefaultBranch  pgtype.Text
	IsActive       bool
	ArchivedAt     pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetRepositoryByID(ctx context.Context, id pgtype.UUID) (GetRepositoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i GetRepositoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubID,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.IsActive,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, organization_id, github_id, name, full_name, default_branch, is_active, archived_at, last_synced_at, created_at, updated_at
FROM repositories
WHERE organization_id = $1
  AND (
    $2 = ''
    OR ($2 = 'active' AND archived_at IS NULL AND is_active = TRUE)
    OR ($2 = 'inactive' AND archived_at IS NULL AND is_active = FALSE)
    OR ($2 = 'archived' AND archived_at IS NOT NULL)
  )
  AND (
    $3 = ''
    OR name ILIKE '%' || $3 || '%'
    OR full_name ILIKE '%' || $3 || '%'
  )
ORDER BY
  CASE WHEN $4 = 'name' AND $5 = 'asc' THEN name END ASC,
  CASE WHEN $4 = 'name' AND $5 = 'desc' THEN name END DESC,
  CASE WHEN $4 = 'fullName' AND $5 = 'asc' THEN full_name END ASC,
  CASE WHEN $4 = 'fullName' AND $5 = 'desc' THEN full_name END DESC,
  CASE WHEN $4 = 'createdAt' AND $5 = 'asc' THEN created_at END ASC,
  CASE WHEN $4 = 'createdAt' AND $5 = 'desc' THEN created_at END DESC,
  id ASC
LIMIT $6
OFFSET $7
`

type ListRepositoriesParams struct {
	OrganizationID pgtype.UUID
	Column2        interface{}
	Column3        interface{}
	Column4        interface{}
	Column5        interface{}
	Limit          int32
	Offset         int32
}

type ListRepositoriesRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	GithubID       int64
	Name           string
	FullName       string
	DefaultBranch  pgtype.Text
	IsActive       bool
	ArchivedAt     pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListRepositories(ctx context.Context, arg ListRepositoriesParams) ([]ListRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, listRepositories,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepositoriesRow
	for rows.Next() {
		var i ListRepositoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.GithubID,
			&i.Name,
			&i.FullName,
			&i.DefaultBranch,
			&i.IsActive,
			&i.ArchivedAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repositoryOrganizationExists = `-- name: RepositoryOrganizationExists :one
SELECT EXISTS (
    SELECT 1
    FROM organizations
    WHERE id = $1
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) RepositoryOrganizationExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, repositoryOrganizationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const syncRepositoryMetadata = `-- name: SyncRepositoryMetadata :exec
UPDATE repositories
SET name = $2,
    full_name = $3,
    default_branch = $4,
    is_active = $5,
    archived_at = $6,
    updated_at = $7
WHERE id = $1
`

type SyncRepositoryMetadataParams struct {
	ID            pgtype.UUID
	Name          string
	FullName      string
	DefaultBranch pgtype.Text
	IsActive      bool
	ArchivedAt    pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) SyncRepositoryMetadata(ctx context.Context, arg SyncRepositoryMetadataParams) error {
	_, err := q.db.Exec(ctx, syncRepositoryMetadata,
		arg.ID,
		arg.Name,
		arg.FullName,
		arg.DefaultBranch,
		arg.IsActive,
		arg.ArchivedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateRepository = `-- name: UpdateRepository :one
UPDATE repositories
SET name = $2,
    full_name = $3,
    default_branch = $4,
    is_active = $5,
    archived_at = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, github_id, name, full_name, default_branch, is_active, archived_at, last_synced_at, created_at, updated_at
`

type UpdateRepositoryParams struct {
	ID            pgtype.UUID
	Name          string
	FullName      string
	DefaultBranch pgtype.Text
	IsActive      bool
	ArchivedAt    pgtype.Timestamptz
}

type UpdateRepositoryRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	GithubID       int64
	Name           string
	FullName       string
	DefaultBranch  pgtype.Text
	IsActive       bool
	ArchivedAt     pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (UpdateRepositoryRow, error) {
	row := q.db.QueryRow(ctx, updateRepository,
		arg.ID,
		arg.Name,
		arg.FullName,
		arg.DefaultBranch,
		arg.IsActive,
		arg.ArchivedAt,
	)
	var i UpdateRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubID,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.IsActive,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepositoryLastSyncedAt = `-- name: UpdateRepositoryLastSyncedAt :exec
UPDATE repositories
SET last_synced_at = $2,
    updated_at = $2
WHERE id = $1
`

type UpdateRepositoryLastSyncedAtParams struct {
	ID           pgtype.UUID
	LastSyncedAt pgtype.Timestamptz
}

func (q *Queries) UpdateRepositoryLastSyncedAt(ctx context.Context, arg UpdateRepositoryLastSyncedAtParams) error {
	_, err := q.db.Exec(ctx, updateRepositoryLastSyncedAt, arg.ID, arg.LastSyncedAt)
	return err
}
