// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_jobs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSyncJobsByRepository = `-- name: CountSyncJobsByRepository :one
SELECT COUNT(*)
FROM sync_jobs
WHERE repository_id = $1
  AND ($2::text IS NULL OR status = $2::text)
`

type CountSyncJobsByRepositoryParams struct {
	RepositoryID pgtype.UUID
	Status       pgtype.Text
}

func (q *Queries) CountSyncJobsByRepository(ctx context.Context, arg CountSyncJobsByRepositoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSyncJobsByRepository, arg.RepositoryID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSyncJob = `-- name: CreateSyncJob :one
INSERT INTO sync_jobs (
    id,
    repository_id,
    status,
    progress,
    triggered_by,
    error_message,
    started_at,
    finished_at,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NOW(),
    NULL
)
RETURNING id, repository_id, status, progress, triggered_by, error_message, started_at, finished_at, created_at, updated_at
`

type CreateSyncJobParams struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

type CreateSyncJobRow struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateSyncJob(ctx context.Context, arg CreateSyncJobParams) (CreateSyncJobRow, error) {
	row := q.db.QueryRow(ctx, createSyncJob,
		arg.ID,
		arg.RepositoryID,
		arg.Status,
		arg.Progress,
		arg.TriggeredBy,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i CreateSyncJobRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.Progress,
		&i.TriggeredBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncJobByID = `-- name: GetSyncJobByID :one
SELECT id, repository_id, status, progress, triggered_by, error_message, started_at, finished_at, created_at, updated_at
FROM sync_jobs
WHERE id = $1
`

type GetSyncJobByIDRow struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetSyncJobByID(ctx context.Context, id pgtype.UUID) (GetSyncJobByIDRow, error) {
	row := q.db.QueryRow(ctx, getSyncJobByID, id)
	var i GetSyncJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.Progress,
		&i.TriggeredBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncJobRepositoryTarget = `-- name: GetSyncJobRepositoryTarget :one
SELECT
    r.id,
    r.full_name,
    r.last_synced_at,
    r.github_installation_repository_id,
    r.is_active,
    gi.installation_id,
    gi.status AS installation_status
FROM repositories r
LEFT JOIN github_installation_repositories gir ON gir.id = r.github_installation_repository_id
LEFT JOIN github_installations gi ON gi.id = gir.github_installation_id
WHERE r.id = $1
`

type GetSyncJobRepositoryTargetRow struct {
	ID                             pgtype.UUID
	FullName                       string
	LastSyncedAt                   pgtype.Timestamptz
	GithubInstallationRepositoryID pgtype.UUID
	IsActive                       bool
	InstallationID                 pgtype.Int8
	InstallationStatus             pgtype.Text
}

func (q *Queries) GetSyncJobRepositoryTarget(ctx context.Context, id pgtype.UUID) (GetSyncJobRepositoryTargetRow, error) {
	row := q.db.QueryRow(ctx, getSyncJobRepositoryTarget, id)
	var i GetSyncJobRepositoryTargetRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.LastSyncedAt,
		&i.GithubInstallationRepositoryID,
		&i.IsActive,
		&i.InstallationID,
		&i.InstallationStatus,
	)
	return i, err
}

const hasActiveSyncJob = `-- name: HasActiveSyncJob :one
SELECT EXISTS (
    SELECT 1
    FROM sync_jobs
    WHERE repository_id = $1
      AND status IN ('pending', 'running')
)
`

func (q *Queries) HasActiveSyncJob(ctx context.Context, repositoryID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveSyncJob, repositoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listPendingSyncJobs = `-- name: ListPendingSyncJobs :many
SELECT id, repository_id, status, progress, triggered_by, error_message, started_at, finished_at, created_at, updated_at
FROM sync_jobs
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

type ListPendingSyncJobsRow struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListPendingSyncJobs(ctx context.Context, limit int32) ([]ListPendingSyncJobsRow, error) {
	rows, err := q.db.Query(ctx, listPendingSyncJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingSyncJobsRow
	for rows.Next() {
		var i ListPendingSyncJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Status,
			&i.Progress,
			&i.TriggeredBy,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncJobsByRepository = `-- name: ListSyncJobsByRepository :many
SELECT id, repository_id, status, progress, triggered_by, error_message, started_at, finished_at, created_at, updated_at
FROM sync_jobs
WHERE repository_id = $1
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY
  CASE
    WHEN $5::text = 'asc' THEN created_at
  END ASC,
  CASE
    WHEN $5::text <> 'asc' THEN created_at
  END DESC,
  id DESC
LIMIT $2
OFFSET $3
`

type ListSyncJobsByRepositoryParams struct {
	RepositoryID pgtype.UUID
	Limit        int32
	Offset       int32
	Status       pgtype.Text
	SortOrder    string
}

type ListSyncJobsByRepositoryRow struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListSyncJobsByRepository(ctx context.Context, arg ListSyncJobsByRepositoryParams) ([]ListSyncJobsByRepositoryRow, error) {
	rows, err := q.db.Query(ctx, listSyncJobsByRepository,
		arg.RepositoryID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncJobsByRepositoryRow
	for rows.Next() {
		var i ListSyncJobsByRepositoryRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Status,
			&i.Progress,
			&i.TriggeredBy,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncJobRepositoryExists = `-- name: SyncJobRepositoryExists :one
SELECT EXISTS (
    SELECT 1
    FROM repositories
    WHERE id = $1
)
`

func (q *Queries) SyncJobRepositoryExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, syncJobRepositoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSyncJobCompleted = `-- name: UpdateSyncJobCompleted :one
UPDATE sync_jobs
SET status = 'completed',
    progress = 100,
    error_message = NULL,
    finished_at = $2,
    updated_at = $2
WHERE id = $1
RETURNING id, repository_id, status, progress, triggered_by, error_message, started_at, finished_at, created_at, updated_at
`

type UpdateSyncJobCompletedParams struct {
	ID         pgtype.UUID
	FinishedAt pgtype.Timestamptz
}

type UpdateSyncJobCompletedRow struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateSyncJobCompleted(ctx context.Context, arg UpdateSyncJobCompletedParams) (UpdateSyncJobCompletedRow, error) {
	row := q.db.QueryRow(ctx, updateSyncJobCompleted, arg.ID, arg.FinishedAt)
	var i UpdateSyncJobCompletedRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.Progress,
		&i.TriggeredBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSyncJobFailed = `-- name: UpdateSyncJobFailed :one
UPDATE sync_jobs
SET status = 'failed',
    error_message = $2,
    finished_at = $3,
    updated_at = $3
WHERE id = $1
RETURNING id, repository_id, status, progress, triggered_by, error_message, started_at, finished_at, created_at, updated_at
`

type UpdateSyncJobFailedParams struct {
	ID           pgtype.UUID
	ErrorMessage pgtype.Text
	FinishedAt   pgtype.Timestamptz
}

type UpdateSyncJobFailedRow struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateSyncJobFailed(ctx context.Context, arg UpdateSyncJobFailedParams) (UpdateSyncJobFailedRow, error) {
	row := q.db.QueryRow(ctx, updateSyncJobFailed, arg.ID, arg.ErrorMessage, arg.FinishedAt)
	var i UpdateSyncJobFailedRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.Progress,
		&i.TriggeredBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSyncJobProgress = `-- name: UpdateSyncJobProgress :one
UPDATE sync_jobs
SET progress = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, repository_id, status, progress, triggered_by, error_message, started_at, finished_at, created_at, updated_at
`

type UpdateSyncJobProgressParams struct {
	ID        pgtype.UUID
	Progress  int32
	UpdatedAt pgtype.Timestamptz
}

type UpdateSyncJobProgressRow struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateSyncJobProgress(ctx context.Context, arg UpdateSyncJobProgressParams) (UpdateSyncJobProgressRow, error) {
	row := q.db.QueryRow(ctx, updateSyncJobProgress, arg.ID, arg.Progress, arg.UpdatedAt)
	var i UpdateSyncJobProgressRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.Progress,
		&i.TriggeredBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSyncJobRunning = `-- name: UpdateSyncJobRunning :one
UPDATE sync_jobs
SET status = 'running',
    progress = $2,
    started_at = COALESCE(started_at, $3),
    finished_at = NULL,
    error_message = NULL,
    updated_at = $3
WHERE id = $1
RETURNING id, repository_id, status, progress, triggered_by, error_message, started_at, finished_at, created_at, updated_at
`

type UpdateSyncJobRunningParams struct {
	ID        pgtype.UUID
	Progress  int32
	UpdatedAt pgtype.Timestamptz
}

type UpdateSyncJobRunningRow struct {
	ID           pgtype.UUID
	RepositoryID pgtype.UUID
	Status       string
	Progress     int32
	TriggeredBy  pgtype.UUID
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateSyncJobRunning(ctx context.Context, arg UpdateSyncJobRunningParams) (UpdateSyncJobRunningRow, error) {
	row := q.db.QueryRow(ctx, updateSyncJobRunning, arg.ID, arg.Progress, arg.UpdatedAt)
	var i UpdateSyncJobRunningRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.Progress,
		&i.TriggeredBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
