// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_deliveries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    id,
    repository_id,
    github_delivery_id,
    event_type,
    processed,
    received_at,
    action,
    payload,
    sync_job_id,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (github_delivery_id) DO NOTHING
RETURNING id, repository_id, github_delivery_id, event_type, processed, received_at, action, payload, sync_job_id, updated_at
`

type CreateWebhookDeliveryParams struct {
	ID               pgtype.UUID
	RepositoryID     pgtype.UUID
	GithubDeliveryID pgtype.Text
	EventType        pgtype.Text
	Processed        bool
	Action           pgtype.Text
	Payload          []byte
	SyncJobID        pgtype.UUID
	UpdatedAt        pgtype.Timestamptz
}

type CreateWebhookDeliveryRow struct {
	ID               pgtype.UUID
	RepositoryID     pgtype.UUID
	GithubDeliveryID pgtype.Text
	EventType        pgtype.Text
	Processed        bool
	ReceivedAt       pgtype.Timestamptz
	Action           pgtype.Text
	Payload          []byte
	SyncJobID        pgtype.UUID
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (CreateWebhookDeliveryRow, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ID,
		arg.RepositoryID,
		arg.GithubDeliveryID,
		arg.EventType,
		arg.Processed,
		arg.Action,
		arg.Payload,
		arg.SyncJobID,
		arg.UpdatedAt,
	)
	var i CreateWebhookDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GithubDeliveryID,
		&i.EventType,
		&i.Processed,
		&i.ReceivedAt,
		&i.Action,
		&i.Payload,
		&i.SyncJobID,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDeliveryByGithubDeliveryID = `-- name: GetWebhookDeliveryByGithubDeliveryID :one
SELECT id, repository_id, github_delivery_id, event_type, processed, received_at, action, payload, sync_job_id, updated_at
FROM webhook_deliveries
WHERE github_delivery_id = $1
`

type GetWebhookDeliveryByGithubDeliveryIDRow struct {
	ID               pgtype.UUID
	RepositoryID     pgtype.UUID
	GithubDeliveryID pgtype.Text
	EventType        pgtype.Text
	Processed        bool
	ReceivedAt       pgtype.Timestamptz
	Action           pgtype.Text
	Payload          []byte
	SyncJobID        pgtype.UUID
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetWebhookDeliveryByGithubDeliveryID(ctx context.Context, githubDeliveryID pgtype.Text) (GetWebhookDeliveryByGithubDeliveryIDRow, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryByGithubDeliveryID, githubDeliveryID)
	var i GetWebhookDeliveryByGithubDeliveryIDRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GithubDeliveryID,
		&i.EventType,
		&i.Processed,
		&i.ReceivedAt,
		&i.Action,
		&i.Payload,
		&i.SyncJobID,
		&i.UpdatedAt,
	)
	return i, err
}

const markWebhookDeliveryProcessed = `-- name: MarkWebhookDeliveryProcessed :one
UPDATE webhook_deliveries
SET processed = $2,
    sync_job_id = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, repository_id, github_delivery_id, event_type, processed, received_at, action, payload, sync_job_id, updated_at
`

type MarkWebhookDeliveryProcessedParams struct {
	ID        pgtype.UUID
	Processed bool
	SyncJobID pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

type MarkWebhookDeliveryProcessedRow struct {
	ID               pgtype.UUID
	RepositoryID     pgtype.UUID
	GithubDeliveryID pgtype.Text
	EventType        pgtype.Text
	Processed        bool
	ReceivedAt       pgtype.Timestamptz
	Action           pgtype.Text
	Payload          []byte
	SyncJobID        pgtype.UUID
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) MarkWebhookDeliveryProcessed(ctx context.Context, arg MarkWebhookDeliveryProcessedParams) (MarkWebhookDeliveryProcessedRow, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryProcessed,
		arg.ID,
		arg.Processed,
		arg.SyncJobID,
		arg.UpdatedAt,
	)
	var i MarkWebhookDeliveryProcessedRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GithubDeliveryID,
		&i.EventType,
		&i.Processed,
		&i.ReceivedAt,
		&i.Action,
		&i.Payload,
		&i.SyncJobID,
		&i.UpdatedAt,
	)
	return i, err
}
